### ISSUE TITLE
Use NanoTTS instead of PicoTTS to avoid writing output WAV files to disk

### ISSUE THREAD

**Issue by mathquis** [rhasspy/rhasspy-tts-cli-hermes#1]
The use of NanoTTS should help avoiding writing TTS WAV output file to disk as it can output RAW audio data directly to stdout.
https://github.com/gmn/nanotts

**Comment by flatsiedatsie** [comment]
Another advantage is that it avoids the rights issues with picoTTS. And it sounds the best of all the current TTS options I've tried too :-)

**Comment by synesthesiam** [comment]
NanoTTS is now in Rhasspy 2.5 :)
